### ISSUE TITLE
Facebook Insights Connector is not working

### ISSUE THREAD

**Issue by prnsit** [Gladior-B-V/data-hub-app#1]
Hello,

When i attach the facebook insight connector, it is loading the screen only, no credentials are adding it. Here is the console error may help you.

Failed to load resource: the server responded with a status of 400 () 
"https://cognito-identity.eu-west-1.amazonaws.com/"

Please help

Thanks,
Pratik Nakrani

**Comment by zoedufrenne** [comment]
Hi Pratik,

We think that in the process when you’ve made the connection to the Facebook Ads connector, some of the toggles turned off instead of on. 
Here a screenshot (in Dutch) and both toggles need to be turned on for a right connection to the Facebook Ads Connector.
 
![image](https://user-images.githubusercontent.com/84766152/168048047-3831ac86-db13-43fa-8e97-4c16459ba649.png)

I’ve you are not sure or want to fix it. 
You can you go to https://www.facebook.com/settings?tab=business_tools&ref=settings and delete the business integration of the Data Hub. If you have done that then you can make a new connection in Data Studio to the Facebook Ads Connector. 

Can you let us know if the connection is been succesfull?
Zoé du Frenne

**Comment by prnsit** [comment]
Hi Zoé,

I have been asking for facebook page insight connection.

BTW it get resolved by RE ATTAHiNG THE WHOLE PROPERTY.

So thanks for your answer
