### ISSUE TITLE
Google Merchant connector limits to 999 records

### ISSUE THREAD

**Issue by andreafuri** [Gladior-B-V/data-hub-app#44]
I've noticed that the Google Merchant connector is only loading 1025 products. I have over 16,000 products in Merchant, and I need all of them to be uploaded.

Is there a limit on the number of records the connector can process? If so, is there a way to remove or increase this limit? Any guidance would be greatly appreciated.

Thank you!

![image](https://github.com/user-attachments/assets/e2f22dd9-5910-4d5c-a880-d09f09037f39)

![image](https://github.com/user-attachments/assets/948c874c-b01c-4d9c-975c-ec1720768620)

**Comment by rkooiker** [comment]
Hi @andreafuri,

You are correct in that our connector only loads the first ~1000 products. This limit was put in place to not strain our servers too much, which keeps it feasible to give away the connectors for free. However, most metrics in this dashboard are still correct. In the case of impressions, clicks and CTR etc. the dashboard loads the metrics for the whole account instead of per product. If you need more detailed information on all of your product we might still be able to help you, but you will have to contact service@gladior.com to inquire about our paid options.
