### ISSUE TITLE
Google Business Profile - Reviews date issue

### ISSUE THREAD

**Issue by never-finish-learning** [Gladior-B-V/data-hub-app#50]
On the date range - if we change the date of the report the reviews page still showing reviews and review data outside that date range.

See image example below - Date range 1st August 2024 - 31st August 2024 yet in the list of reviews it shows a new review from 27th September 2024. I would only expect it to show all reviews post up to the 31st August 2024.

We have tried to play around with the formula in the template but with no joy. Any ideas?

![How To Access Looker Studio Reports - Step 3](https://github.com/user-attachments/assets/53e33422-c277-44b2-9175-c934f4e45c46)

**Comment by rkooiker** [comment]
Hi @never-finish-learning,

Currently the behavior is to fetch the most recent reviews, since this is also the only way we can request the data from your business account. Also keep in mind that there is currently a limit of 50 reviews. We can change this, but for bigger clients that would mean fetching a lot more reviews, which will take much longer. In your case I recommend manually adding a filter on the date field, although I agree that this is not ideal.
