### ISSUE TITLE
Cannot sign in using Google, dashboard lost authorisation to use Data Hub connectors

### ISSUE THREAD

**Issue by Poetszorg** [Gladior-B-V/data-hub-app#6]
Hi,

We have been using the data hub connectors for a few weeks now. All our dashboards just crashed and lost authorisation to use the connectors. I cannot log in on the website or looker studio anymore. We are getting an authorisation issue. If i try to use Google to log in, nothing happens and I cannot get a code to reset my password to the gmail account I used.

![image](https://user-images.githubusercontent.com/122869929/212858273-afe272f8-842f-4799-9c23-fd7f43242000.png)

**Comment by casrooij** [comment]
Hi, I have the same issue!

**Comment by Poetszorg** [comment]
I can login now but my data sources are gone.

**Comment by zoedufrenne** [comment]
Hi,

Thanks for your message.
Due to a technical issue beyond our control, the Data Hub and associated Looker Studio connectors were unavailable from 16 jan. 17:00 CET until yesterday 17 jan. 16:00 CET. The issue has been resolved, but unfortunately the issue resulted in the data credentials becoming unusable for a part of our free users. 
 
Yes, I am experiencing issues with my Looker Studio Dashboard
•	 Update the data sources used in the Looker Studio dashboards and create new credentials
No, I don't experience any issues
•	In that case you can ignore this message.
